version: '3.7'

volumes:
  pgdata:
    driver_opts:
      type: none
      device: ./dbdata
      o: bind
services:
  nginx:
    image: nginx
    environment:
      TZ: Asia/Tokyo
    container_name: container.nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
      - ./nginx/log:/var/log/nginx
    depends_on:
      - web
  web:
    build: .
    environment:
      TZ: Asia/Tokyo
    container_name: container.uwsgi
    command: uwsgi --ini /code/mainproject/django.ini
    volumes:
      - ./src:/code
    expose:
      - "8001"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: container.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    hostname: postgres
