# Generated by Django 3.2.18 on 2023-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('log_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
