# Generated by Django 3.2.18 on 2023-06-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
