# Generated by Django 3.2.16 on 2022-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(default='192.0.0.0'),
            preserve_default=False,
        ),
    ]
