# Generated by Django 3.2.16 on 2022-11-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0003_auto_20221104_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pkg_name',
            new_name='pkgname',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='sv_id',
            new_name='svid',
        ),
    ]
