# Generated by Django 3.2.16 on 2022-11-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0005_auto_20221107_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='pkg_name_tmp',
            new_name='pkg_name',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='sv_id_tmp',
            new_name='sv_id',
        ),
    ]
