# Generated by Django 3.2.16 on 2022-11-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0006_auto_20221107_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pkgname',
            new_name='pkg_name',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='svid',
            new_name='sv_id',
        ),
    ]
