# Generated by Django 3.2.16 on 2022-11-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0007_auto_20221107_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pkg_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
