# Generated by Django 3.2.16 on 2022-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0008_alter_package_pkg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='version',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
