# Generated by Django 3.2.16 on 2022-11-14 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0009_auto_20221114_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='sv_pkg',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
