# Generated by Django 3.2.16 on 2022-11-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0011_auto_20221116_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sv_pkg',
            field=models.SlugField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
