# Generated by Django 3.2.16 on 2022-11-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0013_alter_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='sv_pkg',
            field=models.SlugField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
