# Generated by Django 3.2.16 on 2022-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0011_auto_20221116_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
