# Generated by Django 3.2.16 on 2022-11-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0010_auto_20221114_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='sv_pkg',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
